/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Kiem tra tien trinh con song. Luon tra 200 neu may chu con chay.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Ready
         * @description Kiem tra da san sang phuc vu chua.
         *
         *     Tra 503 khi chua nap duoc mo hinh nhan dien, de bo can bang tai khong
         *     dinh tuyen request vao ban sao nay.
         */
        get: operations["ready_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/recognize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Nhan dien dong xe tu anh
         * @description Nhan dien cac dong xe co trong anh.
         *
         *     Luong xu ly: YOLOv8 khoanh vung xe -> crop -> phan loai 196 lop -> tra
         *     ve top-k kha nang kem thong so ky thuat.
         *
         *     Neu khong phat hien duoc xe nao, he thong phan loai toan bo buc anh
         *     va danh dau `box = null`.
         */
        post: operations["recognize_api_v1_recognize_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cars": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liet ke danh muc xe
         * @description Tra ve danh muc xe, co the loc va phan trang.
         *
         *     Cac bo loc so sanh khong phan biet hoa thuong.
         */
        get: operations["list_cars_api_v1_cars_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cars/filters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Lay cac gia tri hop le de loc
         * @description Tra ve cac gia tri co the dung khi loc.
         *
         *     Giao dien nen goi endpoint nay de dung form thay vi viet cung danh
         *     sach - bang thong so co the thay doi.
         */
        get: operations["get_filters_api_v1_cars_filters_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cars/{class_name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Tra cuu thong so mot dong xe
         * @description Tra cuu thong so theo ten lop day du.
         *
         *     Vi du: `Tesla Model S Sedan 2012`
         */
        get: operations["get_car_api_v1_cars__class_name__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cars/{class_name}/similar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Tim cac xe tuong tu
         * @description Tim cac xe co dac diem gan giong xe da cho.
         */
        get: operations["similar_cars_api_v1_cars__class_name__similar_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/recommend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Goi y xe theo nhu cau
         * @description Goi y xe phu hop voi nhu cau nguoi dung.
         *
         *     Cac dieu kien la RANG BUOC CUNG: xe khong thoa man bi loai han khoi
         *     ket qua. Nguoi dung noi "toi da 800 trieu" thi khong goi y xe 1 ty du
         *     no tot den may.
         *
         *     Danh sach rong nghia la khong co xe nao thoa man - hay noi long dieu
         *     kien.
         */
        post: operations["recommend_api_v1_recommend_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_recognize_api_v1_recognize_post */
        Body_recognize_api_v1_recognize_post: {
            /**
             * File
             * Format: binary
             * @description Anh chua xe can nhan dien
             */
            file: string;
        };
        /**
         * BoundingBox
         * @description Hop bao quanh mot chiec xe trong anh, don vi pixel.
         */
        BoundingBox: {
            /**
             * X1
             * @description Toa do trai
             */
            x1: number;
            /**
             * Y1
             * @description Toa do tren
             */
            y1: number;
            /**
             * X2
             * @description Toa do phai
             */
            x2: number;
            /**
             * Y2
             * @description Toa do duoi
             */
            y2: number;
            /**
             * Confidence
             * @description Do tin cay cua tang phat hien
             */
            confidence: number;
            /**
             * Coco Class
             * @description Lop COCO: car, bus hoac truck
             */
            coco_class: string;
        };
        /**
         * CarListResponse
         * @description Mot trang trong danh muc xe.
         */
        CarListResponse: {
            /**
             * Total
             * @description Tong so xe khop dieu kien loc
             */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Cars */
            cars: components["schemas"]["CarSpecs"][];
        };
        /**
         * CarSpecs
         * @description Thong so ky thuat cua mot dong xe.
         */
        CarSpecs: {
            /**
             * Class Id
             * @description So thu tu goc trong danh muc Stanford Cars (1-196). Khac voi `model_index` trong ket qua du doan.
             */
            class_id: number;
            /** Class Name */
            class_name: string;
            /** Brand */
            brand: string;
            /** Model */
            model: string;
            /** Body Style */
            body_style: string;
            /** Year */
            year: number;
            /** Seats */
            seats: number;
            /** Segment */
            segment: string;
            /**
             * Price Million Vnd
             * @description Gia ban (trieu VND) - SO LIEU MO PHONG
             */
            price_million_vnd: number;
            /**
             * Fuel L Per 100Km
             * @description Muc tieu hao (L/100km) - SO LIEU MO PHONG
             */
            fuel_l_per_100km: number;
        };
        /**
         * DetectedVehicle
         * @description Mot chiec xe da nhan dien, kem thong so va goi y.
         */
        DetectedVehicle: {
            /** @description Hop bao. Bang null khi khong phat hien duoc xe nao va he thong phan loai toan bo buc anh. */
            box?: components["schemas"]["BoundingBox"] | null;
            /** Predictions */
            predictions: components["schemas"]["Prediction"][];
            /**
             * Source
             * @description Mo hinh dua ra ket qua: 'international' (196 dong xe quoc te, doi <=2012) hoac 'vietnam' (20 dong xe thi truong VN, doi 2021-2024). He thong chay ca hai roi chon ket qua dang tin hon.
             * @default international
             */
            source: string;
            /**
             * Is Confident
             * @description Ket qua co vuot nguong dang tin khong
             */
            is_confident: boolean;
            /** @description Thong so cua dong xe co kha nang nhat */
            specs?: components["schemas"]["CarSpecs"] | null;
            /**
             * Similar Cars
             * @description Cac xe tuong tu (chi tra khi yeu cau)
             */
            similar_cars?: components["schemas"]["RecommendedCar"][];
        };
        /**
         * FilterOptions
         * @description Cac gia tri hop le de dung khi loc - cho giao dien dung.
         */
        FilterOptions: {
            /** Body Styles */
            body_styles: string[];
            /** Segments */
            segments: string[];
            /** Price Min */
            price_min: number;
            /** Price Max */
            price_max: number;
            /** Seats Min */
            seats_min: number;
            /** Seats Max */
            seats_max: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthResponse
         * @description Trang thai song cua dich vu.
         */
        HealthResponse: {
            /** Status */
            status: string;
            /** Version */
            version: string;
        };
        /**
         * Prediction
         * @description Mot kha nang ve dong xe, kem xac suat.
         */
        Prediction: {
            /**
             * Model Index
             * @description Chi so dau ra cua mo hinh (0-195). Day KHONG phai `class_id` trong bang thong so - hai he danh so khac nhau. Hay dung `class_name` de doi chieu giua hai noi.
             */
            model_index: number;
            /** Class Name */
            class_name: string;
            /** Confidence */
            confidence: number;
        };
        /**
         * ReadinessResponse
         * @description Trang thai san sang phuc vu (da nap du mo hinh chua).
         */
        ReadinessResponse: {
            /** Status */
            status: string;
            /** Models Loaded */
            models_loaded: boolean;
            /** Car Count */
            car_count: number;
            /** Class Count */
            class_count: number;
            /** Detail */
            detail?: string | null;
        };
        /**
         * RecognitionResponse
         * @description Ket qua nhan dien cho mot buc anh.
         */
        RecognitionResponse: {
            /** Vehicle Count */
            vehicle_count: number;
            /**
             * Likely Not A Car
             * @description True khi nhieu kha nang anh khong chua o to: vua khong phat hien duoc xe, vua phan loai khong chac chan.
             */
            likely_not_a_car: boolean;
            /** Vehicles */
            vehicles: components["schemas"]["DetectedVehicle"][];
            /**
             * Processing Ms
             * @description Thoi gian xu ly, mili giay
             */
            processing_ms: number;
        };
        /**
         * RecommendRequest
         * @description Nhu cau cua nguoi dung de goi y xe.
         *
         *     Cac dieu kien la RANG BUOC CUNG: xe khong thoa man bi loai han khoi
         *     ket qua, khong phai chi bi tru diem.
         */
        RecommendRequest: {
            /**
             * Max Price
             * @description Ngan sach toi da (trieu VND)
             */
            max_price?: number | null;
            /**
             * Min Price
             * @description Gia toi thieu (trieu VND)
             */
            min_price?: number | null;
            /**
             * Min Seats
             * @description So cho ngoi toi thieu
             */
            min_seats?: number | null;
            /**
             * Body Styles
             * @description Cac kieu dang chap nhan duoc
             */
            body_styles?: string[] | null;
            /**
             * Max Fuel
             * @description Muc tieu hao toi da (L/100km)
             */
            max_fuel?: number | null;
            /**
             * Top N
             * @default 5
             */
            top_n: number;
        };
        /**
         * RecommendResponse
         * @description Danh sach xe phu hop voi nhu cau.
         */
        RecommendResponse: {
            /** Count */
            count: number;
            /** Cars */
            cars: components["schemas"]["RecommendedCar"][];
        };
        /**
         * RecommendedCar
         * @description Xe duoc goi y, kem diem phu hop.
         */
        RecommendedCar: {
            /**
             * Class Id
             * @description So thu tu goc trong danh muc Stanford Cars (1-196). Khac voi `model_index` trong ket qua du doan.
             */
            class_id: number;
            /** Class Name */
            class_name: string;
            /** Brand */
            brand: string;
            /** Model */
            model: string;
            /** Body Style */
            body_style: string;
            /** Year */
            year: number;
            /** Seats */
            seats: number;
            /** Segment */
            segment: string;
            /**
             * Price Million Vnd
             * @description Gia ban (trieu VND) - SO LIEU MO PHONG
             */
            price_million_vnd: number;
            /**
             * Fuel L Per 100Km
             * @description Muc tieu hao (L/100km) - SO LIEU MO PHONG
             */
            fuel_l_per_100km: number;
            /**
             * Score
             * @description Diem phu hop, cang cao cang hop
             */
            score: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    ready_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadinessResponse"];
                };
            };
        };
    };
    recognize_api_v1_recognize_post: {
        parameters: {
            query?: {
                top_k?: number;
                /** @description Tra kem cac xe tuong tu */
                include_similar?: boolean;
                similar_count?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_recognize_api_v1_recognize_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecognitionResponse"];
                };
            };
            /** @description File rong hoac anh hong */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description File hoac anh qua lon */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Dinh dang khong duoc ho tro */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Mo hinh nhan dien chua san sang */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_cars_api_v1_cars_get: {
        parameters: {
            query?: {
                /** @description Loc theo hang */
                brand?: string | null;
                body_style?: string | null;
                segment?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CarListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_filters_api_v1_cars_filters_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FilterOptions"];
                };
            };
        };
    };
    get_car_api_v1_cars__class_name__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                class_name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CarSpecs"];
                };
            };
            /** @description Khong tim thay dong xe */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    similar_cars_api_v1_cars__class_name__similar_get: {
        parameters: {
            query?: {
                top_n?: number;
            };
            header?: never;
            path: {
                class_name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecommendResponse"];
                };
            };
            /** @description Khong tim thay dong xe */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    recommend_api_v1_recommend_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecommendRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecommendResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
